services:
  db:
    container_name: jellyhub-db
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=user # your postgres user 
      - POSTGRES_PASSWORD=passwd # your postgres password
      - POSTGRES_DB=jellyhub # your postgres database
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    container_name: jellyhub
    restart: on-failure
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://user:passwd@db:5432/dbname?schema=prisma # make it match with the db service
      - JWT_SECRET=UOt04FdbvhXtmj3keGP981XUj8vJ3uPb # random string for jwt, change it
      - PORT=8888 # optional, default is 3000
    ports:
      - '8888:8888' # make it match with the specified port above, or 3000 to default
    image: zigleur/jellyhub:latest

volumes:
  postgres-data:  