services:
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=ED021205
      - POSTGRES_DB=jellyhub
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    depends_on:
      - db
    ports:
      - '3000:3000'
    environment:
      - DATABASE_URL=postgresql://postgres:ED021205@db:5432/jellyhub?schema=prisma
      - JWT_SECRET=UOt04FdbvhXtmj3keGP981XUj8vJ3uPb
      - NODE_ENV=production

volumes:
  postgres-data:  