/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/__root'
import { Route as MainRouteRouteImport } from './app/_main/route'
import { Route as MainSettingsIndexRouteImport } from './app/_main/settings/index'
import { Route as MainSeriesIndexRouteImport } from './app/_main/series/index'
import { Route as MainMoviesIndexRouteImport } from './app/_main/movies/index'
import { Route as MainAlbumsIndexRouteImport } from './app/_main/albums/index'
import { Route as MainHomeIndexRouteImport } from './app/_main/_home/index'
import { Route as AuthRegisterIndexRouteImport } from './app/_auth/register/index'
import { Route as AuthLoginIndexRouteImport } from './app/_auth/login/index'
import { Route as ApiAuthSplatRouteImport } from './app/api/auth/$'

const MainRouteRoute = MainRouteRouteImport.update({
  id: '/_main',
  getParentRoute: () => rootRouteImport,
} as any)
const MainSettingsIndexRoute = MainSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainSeriesIndexRoute = MainSeriesIndexRouteImport.update({
  id: '/series/',
  path: '/series/',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainMoviesIndexRoute = MainMoviesIndexRouteImport.update({
  id: '/movies/',
  path: '/movies/',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainAlbumsIndexRoute = MainAlbumsIndexRouteImport.update({
  id: '/albums/',
  path: '/albums/',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainHomeIndexRoute = MainHomeIndexRouteImport.update({
  id: '/_home/',
  path: '/',
  getParentRoute: () => MainRouteRoute,
} as any)
const AuthRegisterIndexRoute = AuthRegisterIndexRouteImport.update({
  id: '/_auth/register/',
  path: '/register/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginIndexRoute = AuthLoginIndexRouteImport.update({
  id: '/_auth/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof MainHomeIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/login/': typeof AuthLoginIndexRoute
  '/register/': typeof AuthRegisterIndexRoute
  '/albums/': typeof MainAlbumsIndexRoute
  '/movies/': typeof MainMoviesIndexRoute
  '/series/': typeof MainSeriesIndexRoute
  '/settings/': typeof MainSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/login': typeof AuthLoginIndexRoute
  '/register': typeof AuthRegisterIndexRoute
  '/': typeof MainHomeIndexRoute
  '/albums': typeof MainAlbumsIndexRoute
  '/movies': typeof MainMoviesIndexRoute
  '/series': typeof MainSeriesIndexRoute
  '/settings': typeof MainSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_main': typeof MainRouteRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_auth/login/': typeof AuthLoginIndexRoute
  '/_auth/register/': typeof AuthRegisterIndexRoute
  '/_main/_home/': typeof MainHomeIndexRoute
  '/_main/albums/': typeof MainAlbumsIndexRoute
  '/_main/movies/': typeof MainMoviesIndexRoute
  '/_main/series/': typeof MainSeriesIndexRoute
  '/_main/settings/': typeof MainSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/auth/$'
    | '/login/'
    | '/register/'
    | '/albums/'
    | '/movies/'
    | '/series/'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/api/auth/$'
    | '/login'
    | '/register'
    | '/'
    | '/albums'
    | '/movies'
    | '/series'
    | '/settings'
  id:
    | '__root__'
    | '/_main'
    | '/api/auth/$'
    | '/_auth/login/'
    | '/_auth/register/'
    | '/_main/_home/'
    | '/_main/albums/'
    | '/_main/movies/'
    | '/_main/series/'
    | '/_main/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  MainRouteRoute: typeof MainRouteRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  AuthLoginIndexRoute: typeof AuthLoginIndexRoute
  AuthRegisterIndexRoute: typeof AuthRegisterIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_main': {
      id: '/_main'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MainRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/settings/': {
      id: '/_main/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof MainSettingsIndexRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/series/': {
      id: '/_main/series/'
      path: '/series'
      fullPath: '/series/'
      preLoaderRoute: typeof MainSeriesIndexRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/movies/': {
      id: '/_main/movies/'
      path: '/movies'
      fullPath: '/movies/'
      preLoaderRoute: typeof MainMoviesIndexRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/albums/': {
      id: '/_main/albums/'
      path: '/albums'
      fullPath: '/albums/'
      preLoaderRoute: typeof MainAlbumsIndexRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/_home/': {
      id: '/_main/_home/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MainHomeIndexRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_auth/register/': {
      id: '/_auth/register/'
      path: '/register'
      fullPath: '/register/'
      preLoaderRoute: typeof AuthRegisterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/login/': {
      id: '/_auth/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof AuthLoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface MainRouteRouteChildren {
  MainHomeIndexRoute: typeof MainHomeIndexRoute
  MainAlbumsIndexRoute: typeof MainAlbumsIndexRoute
  MainMoviesIndexRoute: typeof MainMoviesIndexRoute
  MainSeriesIndexRoute: typeof MainSeriesIndexRoute
  MainSettingsIndexRoute: typeof MainSettingsIndexRoute
}

const MainRouteRouteChildren: MainRouteRouteChildren = {
  MainHomeIndexRoute: MainHomeIndexRoute,
  MainAlbumsIndexRoute: MainAlbumsIndexRoute,
  MainMoviesIndexRoute: MainMoviesIndexRoute,
  MainSeriesIndexRoute: MainSeriesIndexRoute,
  MainSettingsIndexRoute: MainSettingsIndexRoute,
}

const MainRouteRouteWithChildren = MainRouteRoute._addFileChildren(
  MainRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  MainRouteRoute: MainRouteRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  AuthLoginIndexRoute: AuthLoginIndexRoute,
  AuthRegisterIndexRoute: AuthRegisterIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
