/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/__root'
import { Route as MainRouteRouteImport } from './app/_main/route'
import { Route as MainAuthRouteRouteImport } from './app/_main/_auth/route'
import { Route as MainHomeRouteRouteImport } from './app/_main/_home/route'
import { Route as GetStartedIndexRouteImport } from './app/get-started/index'
import { Route as MainHomeIndexRouteImport } from './app/_main/_home/index'
import { Route as MainHomeSettingsRouteRouteImport } from './app/_main/_home/settings/route'
import { Route as ApiAuthSplatRouteImport } from './app/api/auth/$'
import { Route as MainAuthLoginIndexRouteImport } from './app/_main/_auth/login/index'
import { Route as MainAuthRegisterIndexRouteImport } from './app/_main/_auth/register/index'
import { Route as MainHomeTypeIndexRouteImport } from './app/_main/_home/$type/index'
import { Route as MainHomeSettingsIndexRouteImport } from './app/_main/_home/settings/index'
import { Route as MainHomeSettingsProfileIndexRouteImport } from './app/_main/_home/settings/profile/index'
import { Route as MainHomeSettingsServersIndexRouteImport } from './app/_main/_home/settings/servers/index'
import { Route as MainHomeSettingsUsersIndexRouteImport } from './app/_main/_home/settings/users/index'

const MainRouteRoute = MainRouteRouteImport.update({
  id: '/_main',
  getParentRoute: () => rootRouteImport,
} as any)
const MainAuthRouteRoute = MainAuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainHomeRouteRoute = MainHomeRouteRouteImport.update({
  id: '/_home',
  getParentRoute: () => MainRouteRoute,
} as any)
const GetStartedIndexRoute = GetStartedIndexRouteImport.update({
  id: '/get-started/',
  path: '/get-started/',
  getParentRoute: () => rootRouteImport,
} as any)
const MainHomeIndexRoute = MainHomeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainHomeRouteRoute,
} as any)
const MainHomeSettingsRouteRoute = MainHomeSettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => MainHomeRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const MainAuthLoginIndexRoute = MainAuthLoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => MainAuthRouteRoute,
} as any)
const MainAuthRegisterIndexRoute = MainAuthRegisterIndexRouteImport.update({
  id: '/register/',
  path: '/register/',
  getParentRoute: () => MainAuthRouteRoute,
} as any)
const MainHomeTypeIndexRoute = MainHomeTypeIndexRouteImport.update({
  id: '/$type/',
  path: '/$type/',
  getParentRoute: () => MainHomeRouteRoute,
} as any)
const MainHomeSettingsIndexRoute = MainHomeSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainHomeSettingsRouteRoute,
} as any)
const MainHomeSettingsProfileIndexRoute =
  MainHomeSettingsProfileIndexRouteImport.update({
    id: '/profile/',
    path: '/profile/',
    getParentRoute: () => MainHomeSettingsRouteRoute,
  } as any)
const MainHomeSettingsServersIndexRoute =
  MainHomeSettingsServersIndexRouteImport.update({
    id: '/servers/',
    path: '/servers/',
    getParentRoute: () => MainHomeSettingsRouteRoute,
  } as any)
const MainHomeSettingsUsersIndexRoute =
  MainHomeSettingsUsersIndexRouteImport.update({
    id: '/users/',
    path: '/users/',
    getParentRoute: () => MainHomeSettingsRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof MainHomeIndexRoute
  '/get-started/': typeof GetStartedIndexRoute
  '/settings': typeof MainHomeSettingsRouteRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/login/': typeof MainAuthLoginIndexRoute
  '/register/': typeof MainAuthRegisterIndexRoute
  '/$type/': typeof MainHomeTypeIndexRoute
  '/settings/': typeof MainHomeSettingsIndexRoute
  '/settings/profile/': typeof MainHomeSettingsProfileIndexRoute
  '/settings/servers/': typeof MainHomeSettingsServersIndexRoute
  '/settings/users/': typeof MainHomeSettingsUsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof MainHomeIndexRoute
  '/get-started': typeof GetStartedIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/login': typeof MainAuthLoginIndexRoute
  '/register': typeof MainAuthRegisterIndexRoute
  '/$type': typeof MainHomeTypeIndexRoute
  '/settings': typeof MainHomeSettingsIndexRoute
  '/settings/profile': typeof MainHomeSettingsProfileIndexRoute
  '/settings/servers': typeof MainHomeSettingsServersIndexRoute
  '/settings/users': typeof MainHomeSettingsUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_main': typeof MainRouteRouteWithChildren
  '/_main/_auth': typeof MainAuthRouteRouteWithChildren
  '/_main/_home': typeof MainHomeRouteRouteWithChildren
  '/get-started/': typeof GetStartedIndexRoute
  '/_main/_home/settings': typeof MainHomeSettingsRouteRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_main/_home/': typeof MainHomeIndexRoute
  '/_main/_auth/login/': typeof MainAuthLoginIndexRoute
  '/_main/_auth/register/': typeof MainAuthRegisterIndexRoute
  '/_main/_home/$type/': typeof MainHomeTypeIndexRoute
  '/_main/_home/settings/': typeof MainHomeSettingsIndexRoute
  '/_main/_home/settings/profile/': typeof MainHomeSettingsProfileIndexRoute
  '/_main/_home/settings/servers/': typeof MainHomeSettingsServersIndexRoute
  '/_main/_home/settings/users/': typeof MainHomeSettingsUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/get-started/'
    | '/settings'
    | '/api/auth/$'
    | '/login/'
    | '/register/'
    | '/$type/'
    | '/settings/'
    | '/settings/profile/'
    | '/settings/servers/'
    | '/settings/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/get-started'
    | '/api/auth/$'
    | '/login'
    | '/register'
    | '/$type'
    | '/settings'
    | '/settings/profile'
    | '/settings/servers'
    | '/settings/users'
  id:
    | '__root__'
    | '/_main'
    | '/_main/_auth'
    | '/_main/_home'
    | '/get-started/'
    | '/_main/_home/settings'
    | '/api/auth/$'
    | '/_main/_home/'
    | '/_main/_auth/login/'
    | '/_main/_auth/register/'
    | '/_main/_home/$type/'
    | '/_main/_home/settings/'
    | '/_main/_home/settings/profile/'
    | '/_main/_home/settings/servers/'
    | '/_main/_home/settings/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  MainRouteRoute: typeof MainRouteRouteWithChildren
  GetStartedIndexRoute: typeof GetStartedIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_main': {
      id: '/_main'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MainRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/_auth': {
      id: '/_main/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MainAuthRouteRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/_home': {
      id: '/_main/_home'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MainHomeRouteRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/get-started/': {
      id: '/get-started/'
      path: '/get-started'
      fullPath: '/get-started/'
      preLoaderRoute: typeof GetStartedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/_home/': {
      id: '/_main/_home/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MainHomeIndexRouteImport
      parentRoute: typeof MainHomeRouteRoute
    }
    '/_main/_home/settings': {
      id: '/_main/_home/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof MainHomeSettingsRouteRouteImport
      parentRoute: typeof MainHomeRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/_auth/login/': {
      id: '/_main/_auth/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof MainAuthLoginIndexRouteImport
      parentRoute: typeof MainAuthRouteRoute
    }
    '/_main/_auth/register/': {
      id: '/_main/_auth/register/'
      path: '/register'
      fullPath: '/register/'
      preLoaderRoute: typeof MainAuthRegisterIndexRouteImport
      parentRoute: typeof MainAuthRouteRoute
    }
    '/_main/_home/$type/': {
      id: '/_main/_home/$type/'
      path: '/$type'
      fullPath: '/$type/'
      preLoaderRoute: typeof MainHomeTypeIndexRouteImport
      parentRoute: typeof MainHomeRouteRoute
    }
    '/_main/_home/settings/': {
      id: '/_main/_home/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof MainHomeSettingsIndexRouteImport
      parentRoute: typeof MainHomeSettingsRouteRoute
    }
    '/_main/_home/settings/profile/': {
      id: '/_main/_home/settings/profile/'
      path: '/profile'
      fullPath: '/settings/profile/'
      preLoaderRoute: typeof MainHomeSettingsProfileIndexRouteImport
      parentRoute: typeof MainHomeSettingsRouteRoute
    }
    '/_main/_home/settings/servers/': {
      id: '/_main/_home/settings/servers/'
      path: '/servers'
      fullPath: '/settings/servers/'
      preLoaderRoute: typeof MainHomeSettingsServersIndexRouteImport
      parentRoute: typeof MainHomeSettingsRouteRoute
    }
    '/_main/_home/settings/users/': {
      id: '/_main/_home/settings/users/'
      path: '/users'
      fullPath: '/settings/users/'
      preLoaderRoute: typeof MainHomeSettingsUsersIndexRouteImport
      parentRoute: typeof MainHomeSettingsRouteRoute
    }
  }
}

interface MainAuthRouteRouteChildren {
  MainAuthLoginIndexRoute: typeof MainAuthLoginIndexRoute
  MainAuthRegisterIndexRoute: typeof MainAuthRegisterIndexRoute
}

const MainAuthRouteRouteChildren: MainAuthRouteRouteChildren = {
  MainAuthLoginIndexRoute: MainAuthLoginIndexRoute,
  MainAuthRegisterIndexRoute: MainAuthRegisterIndexRoute,
}

const MainAuthRouteRouteWithChildren = MainAuthRouteRoute._addFileChildren(
  MainAuthRouteRouteChildren,
)

interface MainHomeSettingsRouteRouteChildren {
  MainHomeSettingsIndexRoute: typeof MainHomeSettingsIndexRoute
  MainHomeSettingsProfileIndexRoute: typeof MainHomeSettingsProfileIndexRoute
  MainHomeSettingsServersIndexRoute: typeof MainHomeSettingsServersIndexRoute
  MainHomeSettingsUsersIndexRoute: typeof MainHomeSettingsUsersIndexRoute
}

const MainHomeSettingsRouteRouteChildren: MainHomeSettingsRouteRouteChildren = {
  MainHomeSettingsIndexRoute: MainHomeSettingsIndexRoute,
  MainHomeSettingsProfileIndexRoute: MainHomeSettingsProfileIndexRoute,
  MainHomeSettingsServersIndexRoute: MainHomeSettingsServersIndexRoute,
  MainHomeSettingsUsersIndexRoute: MainHomeSettingsUsersIndexRoute,
}

const MainHomeSettingsRouteRouteWithChildren =
  MainHomeSettingsRouteRoute._addFileChildren(
    MainHomeSettingsRouteRouteChildren,
  )

interface MainHomeRouteRouteChildren {
  MainHomeSettingsRouteRoute: typeof MainHomeSettingsRouteRouteWithChildren
  MainHomeIndexRoute: typeof MainHomeIndexRoute
  MainHomeTypeIndexRoute: typeof MainHomeTypeIndexRoute
}

const MainHomeRouteRouteChildren: MainHomeRouteRouteChildren = {
  MainHomeSettingsRouteRoute: MainHomeSettingsRouteRouteWithChildren,
  MainHomeIndexRoute: MainHomeIndexRoute,
  MainHomeTypeIndexRoute: MainHomeTypeIndexRoute,
}

const MainHomeRouteRouteWithChildren = MainHomeRouteRoute._addFileChildren(
  MainHomeRouteRouteChildren,
)

interface MainRouteRouteChildren {
  MainAuthRouteRoute: typeof MainAuthRouteRouteWithChildren
  MainHomeRouteRoute: typeof MainHomeRouteRouteWithChildren
}

const MainRouteRouteChildren: MainRouteRouteChildren = {
  MainAuthRouteRoute: MainAuthRouteRouteWithChildren,
  MainHomeRouteRoute: MainHomeRouteRouteWithChildren,
}

const MainRouteRouteWithChildren = MainRouteRoute._addFileChildren(
  MainRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  MainRouteRoute: MainRouteRouteWithChildren,
  GetStartedIndexRoute: GetStartedIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
