/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/__root'
import { Route as MainRouteRouteImport } from './app/_main/route'
import { Route as MainAuthRouteRouteImport } from './app/_main/_auth/route'
import { Route as MainHomeRouteRouteImport } from './app/_main/_home/route'
import { Route as GetStartedIndexRouteImport } from './app/get-started/index'
import { Route as MainHomeIndexRouteImport } from './app/_main/_home/index'
import { Route as ApiAuthSplatRouteImport } from './app/api/auth/$'
import { Route as MainAuthLoginIndexRouteImport } from './app/_main/_auth/login/index'
import { Route as MainAuthRegisterIndexRouteImport } from './app/_main/_auth/register/index'
import { Route as MainHomeAlbumsIndexRouteImport } from './app/_main/_home/albums/index'
import { Route as MainHomeMoviesIndexRouteImport } from './app/_main/_home/movies/index'
import { Route as MainHomeSeriesIndexRouteImport } from './app/_main/_home/series/index'
import { Route as MainHomeSettingsIndexRouteImport } from './app/_main/_home/settings/index'

const MainRouteRoute = MainRouteRouteImport.update({
  id: '/_main',
  getParentRoute: () => rootRouteImport,
} as any)
const MainAuthRouteRoute = MainAuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainHomeRouteRoute = MainHomeRouteRouteImport.update({
  id: '/_home',
  getParentRoute: () => MainRouteRoute,
} as any)
const GetStartedIndexRoute = GetStartedIndexRouteImport.update({
  id: '/get-started/',
  path: '/get-started/',
  getParentRoute: () => rootRouteImport,
} as any)
const MainHomeIndexRoute = MainHomeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainHomeRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const MainAuthLoginIndexRoute = MainAuthLoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => MainAuthRouteRoute,
} as any)
const MainAuthRegisterIndexRoute = MainAuthRegisterIndexRouteImport.update({
  id: '/register/',
  path: '/register/',
  getParentRoute: () => MainAuthRouteRoute,
} as any)
const MainHomeAlbumsIndexRoute = MainHomeAlbumsIndexRouteImport.update({
  id: '/albums/',
  path: '/albums/',
  getParentRoute: () => MainHomeRouteRoute,
} as any)
const MainHomeMoviesIndexRoute = MainHomeMoviesIndexRouteImport.update({
  id: '/movies/',
  path: '/movies/',
  getParentRoute: () => MainHomeRouteRoute,
} as any)
const MainHomeSeriesIndexRoute = MainHomeSeriesIndexRouteImport.update({
  id: '/series/',
  path: '/series/',
  getParentRoute: () => MainHomeRouteRoute,
} as any)
const MainHomeSettingsIndexRoute = MainHomeSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => MainHomeRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof MainHomeIndexRoute
  '/get-started/': typeof GetStartedIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/login/': typeof MainAuthLoginIndexRoute
  '/register/': typeof MainAuthRegisterIndexRoute
  '/albums/': typeof MainHomeAlbumsIndexRoute
  '/movies/': typeof MainHomeMoviesIndexRoute
  '/series/': typeof MainHomeSeriesIndexRoute
  '/settings/': typeof MainHomeSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof MainHomeIndexRoute
  '/get-started': typeof GetStartedIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/login': typeof MainAuthLoginIndexRoute
  '/register': typeof MainAuthRegisterIndexRoute
  '/albums': typeof MainHomeAlbumsIndexRoute
  '/movies': typeof MainHomeMoviesIndexRoute
  '/series': typeof MainHomeSeriesIndexRoute
  '/settings': typeof MainHomeSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_main': typeof MainRouteRouteWithChildren
  '/_main/_auth': typeof MainAuthRouteRouteWithChildren
  '/_main/_home': typeof MainHomeRouteRouteWithChildren
  '/get-started/': typeof GetStartedIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_main/_home/': typeof MainHomeIndexRoute
  '/_main/_auth/login/': typeof MainAuthLoginIndexRoute
  '/_main/_auth/register/': typeof MainAuthRegisterIndexRoute
  '/_main/_home/albums/': typeof MainHomeAlbumsIndexRoute
  '/_main/_home/movies/': typeof MainHomeMoviesIndexRoute
  '/_main/_home/series/': typeof MainHomeSeriesIndexRoute
  '/_main/_home/settings/': typeof MainHomeSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/get-started/'
    | '/api/auth/$'
    | '/login/'
    | '/register/'
    | '/albums/'
    | '/movies/'
    | '/series/'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/get-started'
    | '/api/auth/$'
    | '/login'
    | '/register'
    | '/albums'
    | '/movies'
    | '/series'
    | '/settings'
  id:
    | '__root__'
    | '/_main'
    | '/_main/_auth'
    | '/_main/_home'
    | '/get-started/'
    | '/api/auth/$'
    | '/_main/_home/'
    | '/_main/_auth/login/'
    | '/_main/_auth/register/'
    | '/_main/_home/albums/'
    | '/_main/_home/movies/'
    | '/_main/_home/series/'
    | '/_main/_home/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  MainRouteRoute: typeof MainRouteRouteWithChildren
  GetStartedIndexRoute: typeof GetStartedIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_main': {
      id: '/_main'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MainRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/_auth': {
      id: '/_main/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MainAuthRouteRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/_home': {
      id: '/_main/_home'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MainHomeRouteRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/get-started/': {
      id: '/get-started/'
      path: '/get-started'
      fullPath: '/get-started/'
      preLoaderRoute: typeof GetStartedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/_home/': {
      id: '/_main/_home/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MainHomeIndexRouteImport
      parentRoute: typeof MainHomeRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/_auth/login/': {
      id: '/_main/_auth/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof MainAuthLoginIndexRouteImport
      parentRoute: typeof MainAuthRouteRoute
    }
    '/_main/_auth/register/': {
      id: '/_main/_auth/register/'
      path: '/register'
      fullPath: '/register/'
      preLoaderRoute: typeof MainAuthRegisterIndexRouteImport
      parentRoute: typeof MainAuthRouteRoute
    }
    '/_main/_home/albums/': {
      id: '/_main/_home/albums/'
      path: '/albums'
      fullPath: '/albums/'
      preLoaderRoute: typeof MainHomeAlbumsIndexRouteImport
      parentRoute: typeof MainHomeRouteRoute
    }
    '/_main/_home/movies/': {
      id: '/_main/_home/movies/'
      path: '/movies'
      fullPath: '/movies/'
      preLoaderRoute: typeof MainHomeMoviesIndexRouteImport
      parentRoute: typeof MainHomeRouteRoute
    }
    '/_main/_home/series/': {
      id: '/_main/_home/series/'
      path: '/series'
      fullPath: '/series/'
      preLoaderRoute: typeof MainHomeSeriesIndexRouteImport
      parentRoute: typeof MainHomeRouteRoute
    }
    '/_main/_home/settings/': {
      id: '/_main/_home/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof MainHomeSettingsIndexRouteImport
      parentRoute: typeof MainHomeRouteRoute
    }
  }
}

interface MainAuthRouteRouteChildren {
  MainAuthLoginIndexRoute: typeof MainAuthLoginIndexRoute
  MainAuthRegisterIndexRoute: typeof MainAuthRegisterIndexRoute
}

const MainAuthRouteRouteChildren: MainAuthRouteRouteChildren = {
  MainAuthLoginIndexRoute: MainAuthLoginIndexRoute,
  MainAuthRegisterIndexRoute: MainAuthRegisterIndexRoute,
}

const MainAuthRouteRouteWithChildren = MainAuthRouteRoute._addFileChildren(
  MainAuthRouteRouteChildren,
)

interface MainHomeRouteRouteChildren {
  MainHomeIndexRoute: typeof MainHomeIndexRoute
  MainHomeAlbumsIndexRoute: typeof MainHomeAlbumsIndexRoute
  MainHomeMoviesIndexRoute: typeof MainHomeMoviesIndexRoute
  MainHomeSeriesIndexRoute: typeof MainHomeSeriesIndexRoute
  MainHomeSettingsIndexRoute: typeof MainHomeSettingsIndexRoute
}

const MainHomeRouteRouteChildren: MainHomeRouteRouteChildren = {
  MainHomeIndexRoute: MainHomeIndexRoute,
  MainHomeAlbumsIndexRoute: MainHomeAlbumsIndexRoute,
  MainHomeMoviesIndexRoute: MainHomeMoviesIndexRoute,
  MainHomeSeriesIndexRoute: MainHomeSeriesIndexRoute,
  MainHomeSettingsIndexRoute: MainHomeSettingsIndexRoute,
}

const MainHomeRouteRouteWithChildren = MainHomeRouteRoute._addFileChildren(
  MainHomeRouteRouteChildren,
)

interface MainRouteRouteChildren {
  MainAuthRouteRoute: typeof MainAuthRouteRouteWithChildren
  MainHomeRouteRoute: typeof MainHomeRouteRouteWithChildren
}

const MainRouteRouteChildren: MainRouteRouteChildren = {
  MainAuthRouteRoute: MainAuthRouteRouteWithChildren,
  MainHomeRouteRoute: MainHomeRouteRouteWithChildren,
}

const MainRouteRouteWithChildren = MainRouteRoute._addFileChildren(
  MainRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  MainRouteRoute: MainRouteRouteWithChildren,
  GetStartedIndexRoute: GetStartedIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
