name: CI

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install Dependencies
        run: npm install -g pnpm && pnpm install

      - name: Generate Prisma Client
        run: pnpm prisma generate

      - name: Lint
        run: pnpm lint

      - name: Build
        run: pnpm build
